// <auto-generated />
using GameHaven.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameHaven.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251030151724_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameHaven.Models.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Platform")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReleaseDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Home Page Best Seller",
                            Description = "Take your basketball career to the next level with NBA 2K26.",
                            Genre = "Sports / Simulation",
                            ImageUrl = "/images/homepage/bestsellers/nba2k26.png",
                            Platform = "PS5, PS4, Xbox, PC",
                            Price = 62m,
                            ReleaseDate = "September 2025",
                            Slug = "nba-2k26",
                            Title = "NBA 2K26"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Home Page Best Seller",
                            Description = "Experience the ultimate football simulation in EA FC 26.",
                            Genre = "Sports / Simulation",
                            ImageUrl = "/images/homepage/bestsellers/eafc26.png",
                            Platform = "PS5, PS4, Xbox, PC",
                            Price = 69m,
                            ReleaseDate = "September 2025",
                            Slug = "ea-fc-26",
                            Title = "EA FC 26"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Home Page Best Seller",
                            Description = "Step into the ring and become a wrestling champion in WWE 2K25.",
                            Genre = "Sports / Action",
                            ImageUrl = "/images/homepage/bestsellers/wwe2k25.png",
                            Platform = "PS5, PS4, Xbox, PC",
                            Price = 25m,
                            ReleaseDate = "March 2025",
                            Slug = "wwe-2k25",
                            Title = "WWE 2K25"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Home Page Best Seller",
                            Description = "Explore Los Santos in this epic open-world crime adventure.",
                            Genre = "Action / Adventure",
                            ImageUrl = "/images/homepage/bestsellers/gta5.png",
                            Platform = "PS5, PS4, Xbox, PC",
                            Price = 40m,
                            ReleaseDate = "March 2022",
                            Slug = "gta-5",
                            Title = "GTA 5"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Home Page Best Seller",
                            Description = "Engage in intense warfare in the latest Call of Duty Black Ops game.",
                            Genre = "Shooter / Action",
                            ImageUrl = "/images/homepage/bestsellers/codbo6.png",
                            Platform = "PS5, PS4, Xbox, PC",
                            Price = 39m,
                            ReleaseDate = "October 2024",
                            Slug = "cod-black-ops-6",
                            Title = "COD Black Ops 6"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Home Page Best Seller",
                            Description = "Loot, shoot and explore the chaotic world of Borderlands 4.",
                            Genre = "Shooter / RPG",
                            ImageUrl = "/images/homepage/bestsellers/borderlands4.png",
                            Platform = "PS5, PS4, Xbox, PC",
                            Price = 58m,
                            ReleaseDate = "September 2025",
                            Slug = "borderlands-4",
                            Title = "Borderlands 4"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Home Page Best Seller",
                            Description = "Venture into dark, twisted worlds in this chilling platformer.",
                            Genre = "Horror / Platformer",
                            ImageUrl = "/images/homepage/bestsellers/little-nightmares-3.png",
                            Platform = "PS5, PS4, Switch, PC",
                            Price = 35m,
                            ReleaseDate = "October 2025",
                            Slug = "little-nightmares-3",
                            Title = "Little Nightmares III"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Home Page Best Seller",
                            Description = "Embark on a stealthy adventure full of intrigue.",
                            Genre = "Action / Stealth",
                            ImageUrl = "/images/homepage/bestsellers/assassins-creed-shadows.png",
                            Platform = "PS5, PS4, Xbox, PC",
                            Price = 40m,
                            ReleaseDate = "March 2025",
                            Slug = "assassins-creed-shadows",
                            Title = "Assassin’s Creed Shadows"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Home Page Best Seller",
                            Description = "Catch, train and battle in the latest Pokémon adventure.",
                            Genre = "Adventure / RPG",
                            ImageUrl = "/images/homepage/bestsellers/pokemon-legends-za.png",
                            Platform = "Switch",
                            Price = 32m,
                            ReleaseDate = "October 2025",
                            Slug = "pokemon-legends-za",
                            Title = "Pokémon Legends Z-A"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Home Page Best Seller",
                            Description = "Race at lightning speed across amazing worlds with Sonic and friends.",
                            Genre = "Racing / Arcade",
                            ImageUrl = "/images/homepage/bestsellers/sonic-racing-crossworlds.png",
                            Platform = "Switch",
                            Price = 43m,
                            ReleaseDate = "September 2025",
                            Slug = "sonic-racing-crossworlds",
                            Title = "Sonic Racing: CrossWorlds"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Nintendo Accessories",
                            Description = "High-quality dock for Nintendo Switch with extra HDMI support.",
                            Genre = "Nintendo Accessory",
                            ImageUrl = "/images/nintendo/accessories/switch-dock-set.png",
                            Platform = "Nintendo Switch",
                            Price = 120m,
                            ReleaseDate = "June 2025",
                            Slug = "switch-dock-set",
                            Title = "Nintendo Switch Dock Set"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Nintendo Accessories",
                            Description = "Protect your console on the go with this durable case and screen protector.",
                            Genre = "Nintendo Accessory",
                            ImageUrl = "/images/nintendo/accessories/switch-case-screen-protector.png",
                            Platform = "Nintendo Switch",
                            Price = 30m,
                            ReleaseDate = "June 2025",
                            Slug = "switch-case-screen-protector",
                            Title = "Nintendo Switch Carrying Case + Screen Protector"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Nintendo Accessories",
                            Description = "Charge your Joy-Cons while you play for uninterrupted gaming.",
                            Genre = "Nintendo Accessory",
                            ImageUrl = "/images/nintendo/accessories/joycon-charging-grip.png",
                            Platform = "Nintendo Switch",
                            Price = 13m,
                            ReleaseDate = "October 2024",
                            Slug = "joycon-charging-grip",
                            Title = "Nintendo Switch Joy-Con Charging Grip"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Nintendo Accessories",
                            Description = "Comfortable leg strap accessory for Ring Fit Adventure.",
                            Genre = "Nintendo Accessory",
                            ImageUrl = "/images/nintendo/accessories/switch-leg-strap.png",
                            Platform = "Nintendo Switch",
                            Price = 15m,
                            ReleaseDate = "April 2922",
                            Slug = "switch-leg-strap",
                            Title = "Nintendo Switch Leg Strap"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Nintendo Accessories",
                            Description = "Official AC adapter to keep your Switch charged.",
                            Genre = "Nintendo Accessory",
                            ImageUrl = "/images/nintendo/accessories/switch-ac-adapter.png",
                            Platform = "Nintendo Switch",
                            Price = 15m,
                            ReleaseDate = "March 2017",
                            Slug = "switch-ac-adapter",
                            Title = "Nintendo Switch AC Adapter"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Nintendo Console",
                            Description = "Next-gen Nintendo Switch with improved graphics and battery life.",
                            Genre = "Nintendo Console",
                            ImageUrl = "/images/nintendo/consoles/switch2.png",
                            Platform = "Nintendo Switch",
                            Price = 380m,
                            ReleaseDate = "June 2025",
                            Slug = "switch-2",
                            Title = "Nintendo Switch 2"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Nintendo Console",
                            Description = "Special edition Lite console with Zelda-themed design.",
                            Genre = "Nintendo Console",
                            ImageUrl = "/images/nintendo/consoles/switch-lite-hyrule.png",
                            Platform = "Nintendo Switch",
                            Price = 250m,
                            ReleaseDate = "September 2024",
                            Slug = "switch-lite-hyrule",
                            Title = "Switch Lite Hyrule Edition"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Nintendo Console",
                            Description = "Enhanced OLED display console for Nintendo Switch.",
                            Genre = "Nintendo Console",
                            ImageUrl = "/images/nintendo/consoles/switch-oled.png",
                            Platform = "Nintendo Switch",
                            Price = 274m,
                            ReleaseDate = "October 2021",
                            Slug = "switch-oled",
                            Title = "Switch OLED"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Nintendo Console",
                            Description = "Compact and portable Nintendo Switch Lite in Yellow.",
                            Genre = "Nintendo Console",
                            ImageUrl = "/images/nintendo/consoles/switch-lite-yellow.png",
                            Platform = "Nintendo Switch",
                            Price = 170m,
                            ReleaseDate = "September 2019",
                            Slug = "switch-lite-yellow",
                            Title = "Switch Lite (Yellow)"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Nintendo Console",
                            Description = "Standard Nintendo Switch Lite for portable gaming.",
                            Genre = "Nintendo Console",
                            ImageUrl = "/images/nintendo/consoles/switch-lite2.png",
                            Platform = "Nintendo Switch",
                            Price = 184m,
                            ReleaseDate = "September 2019",
                            Slug = "switch-lite2",
                            Title = "Nintendo Switch Lite"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Nintendo Game",
                            Description = "Embark on a brand new Pokémon adventure with Scarlet edition.",
                            Genre = "Nintendo Game",
                            ImageUrl = "/images/nintendo/games/pokemon-scarlet.png",
                            Platform = "Nintendo Switch",
                            Price = 38m,
                            ReleaseDate = "November 2022",
                            Slug = "pokemon-scarlet",
                            Title = "Pokémon Scarlet"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Nintendo Game",
                            Description = "Explore the regions of Violet and catch new Pokémon.",
                            Genre = "Nintendo Game",
                            ImageUrl = "/images/nintendo/games/pokemon-violet.png",
                            Platform = "Nintendo Switch",
                            Price = 38m,
                            ReleaseDate = "November 2022",
                            Slug = "pokemon-violet",
                            Title = "Pokémon Violet"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Nintendo Game",
                            Description = "Join Mario & Luigi in a brand-new cooperative adventure.",
                            Genre = "Nintendo Game",
                            ImageUrl = "/images/nintendo/games/mario-luigi-brothership.png",
                            Platform = "Nintendo Switch",
                            Price = 29m,
                            ReleaseDate = "November 2024",
                            Slug = "mario-luigi-brothership",
                            Title = "Mario & Luigi: Brothership"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Nintendo Game",
                            Description = "Two exciting adventures in one package.",
                            Genre = "Nintendo Game",
                            ImageUrl = "/images/nintendo/games/super-mario-3d-world-bowsers-fury.png",
                            Platform = "Nintendo Switch",
                            Price = 38m,
                            ReleaseDate = "February 2021",
                            Slug = "super-mario-3d-world-bowsers-fury",
                            Title = "Super Mario 3D World + Bowser’s Fury"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Nintendo Game",
                            Description = "High-speed drag racing on Nintendo Switch.",
                            Genre = "Nintendo Game",
                            ImageUrl = "/images/nintendo/games/drag-drive.png",
                            Platform = "Nintendo Switch",
                            Price = 17m,
                            ReleaseDate = "August 2025",
                            Slug = "drag-drive",
                            Title = "Drag x Drive"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Nintendo New In",
                            Description = "Epic new Zelda adventure across Hyrule.",
                            Genre = "Nintendo New In",
                            ImageUrl = "/images/nintendo/newin/the-legend-of-zelda-tears-of-the-kingdom.png",
                            Platform = "Nintendo Switch",
                            Price = 60m,
                            ReleaseDate = "May 2023",
                            Slug = "zelda-tears-of-the-kingdom",
                            Title = "The Legend of Zelda: Tears of the Kingdom"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Nintendo New In",
                            Description = "Party with friends in Mario's latest mini-game extravaganza.",
                            Genre = "Nintendo New In",
                            ImageUrl = "/images/nintendo/newin/super-mario-party-jamboree.png",
                            Platform = "Nintendo Switch",
                            Price = 38m,
                            ReleaseDate = "October 2024",
                            Slug = "super-mario-party-jamboree",
                            Title = "Super Mario Party Jamboree"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Nintendo New In",
                            Description = "Swing through barrels and beat the competition.",
                            Genre = "Nintendo New In",
                            ImageUrl = "/images/nintendo/newin/donkey-kong-bananza.png",
                            Platform = "Nintendo Switch",
                            Price = 57m,
                            ReleaseDate = "July 2025",
                            Slug = "donkey-kong-bananza",
                            Title = "Donkey Kong Bananza"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Nintendo New In",
                            Description = "Explore new regions and legendary Pokémon.",
                            Genre = "Nintendo New In",
                            ImageUrl = "/images/nintendo/newin/pokémon-legends-Z-A.png",
                            Platform = "Nintendo Switch",
                            Price = 42m,
                            ReleaseDate = "October 2025",
                            Slug = "pokemon-legends-za",
                            Title = "Pokémon Legends: Z-A"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Nintendo New In",
                            Description = "Race around the world in this exciting Mario Kart edition.",
                            Genre = "Nintendo New In",
                            ImageUrl = "/images/nintendo/newin/mario-kart-world.png",
                            Platform = "Nintendo Switch",
                            Price = 60m,
                            ReleaseDate = "June 2025",
                            Slug = "mario-kart-world",
                            Title = "Mario Kart World"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Nintendo New In",
                            Description = "New Metroid adventure with enhanced gameplay.",
                            Genre = "Nintendo New In",
                            ImageUrl = "/images/nintendo/newin/metroid-prime-4-beyond.png",
                            Platform = "Nintendo Switch",
                            Price = 50m,
                            ReleaseDate = "June 2025",
                            Slug = "metroid-prime-4-beyond",
                            Title = "Metroid Prime 4: Beyond"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Nintendo New In",
                            Description = "Fast-paced racing with Sonic and friends.",
                            Genre = "Nintendo New In",
                            ImageUrl = "/images/nintendo/newin/sonic-racing-crossWorlds.png",
                            Platform = "Nintendo Switch",
                            Price = 43m,
                            ReleaseDate = "September 2025",
                            Slug = "sonic-racing-crossworlds",
                            Title = "Sonic Racing: CrossWorlds"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Nintendo New In",
                            Description = "Spooky and thrilling adventures await.",
                            Genre = "Nintendo New In",
                            ImageUrl = "/images/nintendo/newin/little-nightmares-3-nintendo-switch.png",
                            Platform = "Nintendo Switch",
                            Price = 33m,
                            ReleaseDate = "October 2025",
                            Slug = "little-nightmares-3-ns",
                            Title = "Little Nightmares III Nintendo Switch"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Nintendo New In",
                            Description = "Take your football game on the go.",
                            Genre = "Nintendo New In",
                            ImageUrl = "/images/nintendo/newin/ea-sports-fc-26-nintendo-switch.png",
                            Platform = "Nintendo Switch",
                            Price = 45m,
                            ReleaseDate = "September 2025",
                            Slug = "ea-fc-26-ns",
                            Title = "EA Sports FC 26 Nintendo Switch"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Nintendo New In",
                            Description = "Creative building and party fun in one game.",
                            Genre = "Nintendo New In",
                            ImageUrl = "/images/nintendo/newin/lego-party.png",
                            Platform = "Nintendo Switch",
                            Price = 39m,
                            ReleaseDate = "September 2025",
                            Slug = "lego-party",
                            Title = "LEGO Party"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Xbox Accessories",
                            Description = "Stay powered with the official rechargeable battery pack and USB-C cable.",
                            Genre = "Xbox Accessory",
                            ImageUrl = "/images/xbox/accessories/xbox-battery-usbc.png",
                            Platform = "Xbox Series X|S",
                            Price = 20m,
                            ReleaseDate = "November 2020",
                            Slug = "xbox-battery-usbc",
                            Title = "Xbox Rechargeable Battery + USB-C Cable"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Xbox Accessories",
                            Description = "Experience the modern Xbox controller design with enhanced comfort and precision.",
                            Genre = "Xbox Accessory",
                            ImageUrl = "/images/xbox/accessories/xbox-controller-standard.png",
                            Platform = "Xbox Series X|S",
                            Price = 50m,
                            ReleaseDate = "November 2020",
                            Slug = "xbox-controller-standard",
                            Title = "Xbox Wireless Controller (Standard)"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Xbox Accessories",
                            Description = "High-performance controller with interchangeable thumbsticks and paddles.",
                            Genre = "Xbox Accessory",
                            ImageUrl = "/images/xbox/accessories/xbox-elite-controller-series2.png",
                            Platform = "Xbox Series X|S",
                            Price = 150m,
                            ReleaseDate = "November 2019",
                            Slug = "xbox-elite-controller-series2",
                            Title = "Xbox Elite Wireless Controller Series 2"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Xbox Accessories",
                            Description = "Immerse yourself with crystal-clear sound and wireless freedom.",
                            Genre = "Xbox Accessory",
                            ImageUrl = "/images/xbox/accessories/xbox-wireless-headset.png",
                            Platform = "Xbox Series X|S",
                            Price = 110m,
                            ReleaseDate = "March 2021",
                            Slug = "xbox-wireless-headset",
                            Title = "Xbox Wireless Headset"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Xbox Accessories",
                            Description = "Comfortable wired headset delivering rich, clear audio.",
                            Genre = "Xbox Accessory",
                            ImageUrl = "/images/xbox/accessories/xbox-stereo-headset.png",
                            Platform = "Xbox Series X|S",
                            Price = 45m,
                            ReleaseDate = "September 2021",
                            Slug = "xbox-stereo-headset",
                            Title = "Xbox Stereo Headset"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Xbox Console",
                            Description = "Compact next-gen console delivering powerful performance in a smaller size.",
                            Genre = "Xbox Console",
                            ImageUrl = "/images/xbox/consoles/xbox-series-s-512.png",
                            Platform = "Xbox Series S",
                            Price = 300m,
                            ReleaseDate = "November 2020",
                            Slug = "xbox-series-s-512",
                            Title = "Xbox Series S (512 GB)"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Xbox Console",
                            Description = "The fastest, most powerful Xbox console ever built.",
                            Genre = "Xbox Console",
                            ImageUrl = "/images/xbox/consoles/xbox-series-x-1tb.png",
                            Platform = "Xbox Series X",
                            Price = 500m,
                            ReleaseDate = "November 2020",
                            Slug = "xbox-series-x-1tb",
                            Title = "Xbox Series X (1 TB)"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Xbox Console",
                            Description = "All-digital edition of the Xbox Series X with 1TB storage.",
                            Genre = "Xbox Console",
                            ImageUrl = "/images/xbox/consoles/xbox-series-x-digital-1tb.png",
                            Platform = "Xbox Series X",
                            Price = 450m,
                            ReleaseDate = "October 2024",
                            Slug = "xbox-series-x-digital-1tb",
                            Title = "Xbox Series X - Digital Edition (1 TB)"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Xbox Console",
                            Description = "Digital-only console with larger 1TB SSD storage.",
                            Genre = "Xbox Console",
                            ImageUrl = "/images/xbox/consoles/xbox-series-s-1tb.png",
                            Platform = "Xbox Series S",
                            Price = 330m,
                            ReleaseDate = "September 2023",
                            Slug = "xbox-series-s-1tb",
                            Title = "Xbox Series S (1 TB)"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Xbox Console",
                            Description = "Classic Xbox One console for gaming, entertainment, and media.",
                            Genre = "Xbox Console",
                            ImageUrl = "/images/xbox/consoles/xbox-one.png",
                            Platform = "Xbox One",
                            Price = 150m,
                            ReleaseDate = "November 2013",
                            Slug = "xbox-one",
                            Title = "Xbox One"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Xbox Game",
                            Description = "Explore chaotic worlds and collect tons of loot in the latest Borderlands adventure.",
                            Genre = "Xbox Game",
                            ImageUrl = "/images/xbox/games/borderlands4.png",
                            Platform = "Xbox Series X|S",
                            Price = 58m,
                            ReleaseDate = "September 2025",
                            Slug = "borderlands-4",
                            Title = "Borderlands 4"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Xbox Game",
                            Description = "Fast-paced combat and deadly precision return in this action-packed sequel.",
                            Genre = "Xbox Game",
                            ImageUrl = "/images/xbox/games/ninja-gaiden-4.png",
                            Platform = "Xbox Series X|S",
                            Price = 50m,
                            ReleaseDate = "October 2025",
                            Slug = "ninja-gaiden-4",
                            Title = "Ninja Gaiden 4"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Xbox Game",
                            Description = "Build an empire that will stand the test of time in this new strategy masterpiece.",
                            Genre = "Xbox Game",
                            ImageUrl = "/images/xbox/games/civilization7-2.png",
                            Platform = "Xbox Series X|S",
                            Price = 40m,
                            ReleaseDate = "February 2025",
                            Slug = "civilization-7",
                            Title = "Civilization VII"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Xbox Game",
                            Description = "Journey through Feudal Japan in Ubisoft’s next-generation adventure.",
                            Genre = "Xbox Game",
                            ImageUrl = "/images/xbox/games/assassins-creed-shadows-2.png",
                            Platform = "Xbox Series X|S",
                            Price = 40m,
                            ReleaseDate = "March 2025",
                            Slug = "assassins-creed-shadows",
                            Title = "Assassin’s Creed Shadows"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Xbox Game",
                            Description = "Survive the cursed Wild West in this dark FPS horror experience.",
                            Genre = "Xbox Game",
                            ImageUrl = "/images/xbox/games/blood-west-2.png",
                            Platform = "Xbox Series X|S",
                            Price = 34.99m,
                            ReleaseDate = "February 2022",
                            Slug = "blood-west",
                            Title = "Blood West"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Xbox New In",
                            Description = "Survive the cursed Wild West in this eerie first-person horror.",
                            Genre = "Xbox New In",
                            ImageUrl = "/images/xbox/newin/blood-west.png",
                            Platform = "Xbox Series X|S",
                            Price = 34.99m,
                            ReleaseDate = "February 2022",
                            Slug = "blood-west-newin",
                            Title = "Blood West"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Xbox New In",
                            Description = "Sharpen your blade in the next generation of fast-paced ninja action.",
                            Genre = "Xbox New In",
                            ImageUrl = "/images/xbox/newin/ninja-gaiden-4.png",
                            Platform = "Xbox Series X|S",
                            Price = 59.99m,
                            ReleaseDate = "October 2025",
                            Slug = "ninja-gaiden-4-newin",
                            Title = "Ninja Gaiden 4"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Xbox New In",
                            Description = "Return to the shadows in the most intense Black Ops yet.",
                            Genre = "Xbox New In",
                            ImageUrl = "/images/xbox/newin/cod-black-ops-7.png",
                            Platform = "Xbox Series X|S",
                            Price = 69.99m,
                            ReleaseDate = "November 2025",
                            Slug = "cod-black-ops-7",
                            Title = "Call of Duty: Black Ops 7"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Xbox New In",
                            Description = "Revisit the origins of the Gears saga with next-gen visuals.",
                            Genre = "Xbox New In",
                            ImageUrl = "/images/xbox/newin/gears-of-war-reloaded.png",
                            Platform = "Xbox Series X|S",
                            Price = 64.99m,
                            ReleaseDate = "August 2025",
                            Slug = "gears-of-war-reloaded",
                            Title = "Gears of War Reloaded"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Xbox New In",
                            Description = "Skate through remastered classics with new features and levels.",
                            Genre = "Xbox New In",
                            ImageUrl = "/images/xbox/newin/tony-hawk-pro-skater-3-4.png",
                            Platform = "Xbox Series X|S",
                            Price = 44.99m,
                            ReleaseDate = "July 2025",
                            Slug = "tony-hawk-pro-skater-3-4",
                            Title = "Tony Hawk Pro Skater 3+4"
                        },
                        new
                        {
                            Id = 56,
                            Category = "Xbox New In",
                            Description = "The bizarre comedy FPS returns with even more talking weapons.",
                            Genre = "Xbox New In",
                            ImageUrl = "/images/xbox/newin/high-on-life.png",
                            Platform = "Xbox Series X|S",
                            Price = 39.99m,
                            ReleaseDate = "November 2025",
                            Slug = "high-on-life-2",
                            Title = "High on Life 2"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Xbox New In",
                            Description = "Rediscover a beloved classic reimagined for modern consoles.",
                            Genre = "Xbox New In",
                            ImageUrl = "/images/xbox/newin/persona-4-remake.png",
                            Platform = "Xbox Series X|S",
                            Price = 54.99m,
                            ReleaseDate = "June 2025",
                            Slug = "persona-4-remake",
                            Title = "Persona 4 Remake"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Xbox New In",
                            Description = "Embark on a new galactic journey in this space-faring RPG sequel.",
                            Genre = "Xbox New In",
                            ImageUrl = "/images/xbox/newin/outer-worlds-2.png",
                            Platform = "Xbox Series X|S",
                            Price = 59.99m,
                            ReleaseDate = "October 2025",
                            Slug = "outer-worlds-2",
                            Title = "The Outer Worlds 2"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Xbox New In",
                            Description = "Experience an epic fantasy story full of intrigue and stunning visuals.",
                            Genre = "Xbox New In",
                            ImageUrl = "/images/xbox/newin/final-fantasy-16.png",
                            Platform = "Xbox Series X|S",
                            Price = 49.99m,
                            ReleaseDate = "June 2023",
                            Slug = "final-fantasy-16",
                            Title = "Final Fantasy XVI"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Xbox New In",
                            Description = "Protect your realm in this visually stunning action RPG.",
                            Genre = "Xbox New In",
                            ImageUrl = "/images/xbox/newin/keeper.png",
                            Platform = "Xbox Series X|S",
                            Price = 49.99m,
                            ReleaseDate = "November 2025",
                            Slug = "keeper",
                            Title = "Keeper"
                        },
                        new
                        {
                            Id = 61,
                            Category = "PlayStation Accessories",
                            Description = "Charge your DualSense controllers quickly and safely.",
                            Genre = "PlayStation Accessory",
                            ImageUrl = "/images/playstation/accessories/dualsense-charging-station.png",
                            Platform = "PlayStation 5",
                            Price = 25m,
                            ReleaseDate = "November 2020",
                            Slug = "dualsense-charging-station",
                            Title = "DualSense Charging Station"
                        },
                        new
                        {
                            Id = 62,
                            Category = "PlayStation Accessories",
                            Description = "Stream in high definition with the PS5 HD Camera.",
                            Genre = "PlayStation Accessory",
                            ImageUrl = "/images/playstation/accessories/ps5-hd-camera.png",
                            Platform = "PlayStation 5",
                            Price = 48m,
                            ReleaseDate = "November 2020",
                            Slug = "ps5-hd-camera",
                            Title = "PlayStation 5 HD Camera"
                        },
                        new
                        {
                            Id = 63,
                            Category = "PlayStation Accessories",
                            Description = "Immersive 3D audio experience for PS5.",
                            Genre = "PlayStation Accessory",
                            ImageUrl = "/images/playstation/accessories/pulse3d-headset.png",
                            Platform = "PlayStation 5",
                            Price = 130m,
                            ReleaseDate = "October 2020",
                            Slug = "pulse3d-headset",
                            Title = "Pulse 3D Wireless Headset"
                        },
                        new
                        {
                            Id = 64,
                            Category = "PlayStation Accessories",
                            Description = "Next-gen controller with adaptive triggers.",
                            Genre = "PlayStation Accessory",
                            ImageUrl = "/images/playstation/accessories/dualsense-controller.png",
                            Platform = "PlayStation 5",
                            Price = 60m,
                            ReleaseDate = "November 2020",
                            Slug = "dualsense-controller",
                            Title = "DualSense Wireless Controller (PS5)"
                        },
                        new
                        {
                            Id = 65,
                            Category = "PlayStation Accessories",
                            Description = "Control media playback easily on your PS5.",
                            Genre = "PlayStation Accessory",
                            ImageUrl = "/images/playstation/accessories/ps5-media-remote.png",
                            Platform = "PlayStation 5",
                            Price = 33m,
                            ReleaseDate = "November 2020",
                            Slug = "ps5-media-remote",
                            Title = "PlayStation 5 Media Remote"
                        },
                        new
                        {
                            Id = 66,
                            Category = "PlayStation Consoles",
                            Description = "Next-gen console with 4K gaming and ultra-fast SSD.",
                            Genre = "PlayStation Console",
                            ImageUrl = "/images/playstation/consoles/ps5-standard.png",
                            Platform = "PlayStation 5",
                            Price = 479m,
                            ReleaseDate = "November 2020",
                            Slug = "ps5-standard",
                            Title = "PlayStation 5 Standard"
                        },
                        new
                        {
                            Id = 67,
                            Category = "PlayStation Consoles",
                            Description = "All-digital PS5 with full next-gen features.",
                            Genre = "PlayStation Console",
                            ImageUrl = "/images/playstation/consoles/ps5-digital.png",
                            Platform = "PlayStation 5",
                            Price = 399m,
                            ReleaseDate = "November 2020",
                            Slug = "ps5-digital",
                            Title = "PlayStation 5 Digital Edition"
                        },
                        new
                        {
                            Id = 68,
                            Category = "PlayStation Consoles",
                            Description = "Enhanced PS4 experience with improved graphics.",
                            Genre = "PlayStation Console",
                            ImageUrl = "/images/playstation/consoles/ps4-pro.png",
                            Platform = "PlayStation 4",
                            Price = 279m,
                            ReleaseDate = "November 2016",
                            Slug = "ps4-pro",
                            Title = "PlayStation 4 Pro"
                        },
                        new
                        {
                            Id = 69,
                            Category = "PlayStation Consoles",
                            Description = "Slimline PS4 with compact design and reliable performance.",
                            Genre = "PlayStation Console",
                            ImageUrl = "/images/playstation/consoles/ps4-slim.png",
                            Platform = "PlayStation 4",
                            Price = 150m,
                            ReleaseDate = "September 2016",
                            Slug = "ps4-slim",
                            Title = "PlayStation 4 Slim (500GB)"
                        },
                        new
                        {
                            Id = 70,
                            Category = "PlayStation Consoles",
                            Description = "PS4 with Call of Duty: WW2 bundle included.",
                            Genre = "PlayStation Console",
                            ImageUrl = "/images/playstation/consoles/ps4-ww2-bundle.png",
                            Platform = "PlayStation 4",
                            Price = 245m,
                            ReleaseDate = "November 2017",
                            Slug = "ps4-ww2-bundle",
                            Title = "PlayStation 4 WW2 Bundle"
                        },
                        new
                        {
                            Id = 71,
                            Category = "PlayStation Games",
                            Description = "Experience next-gen large-scale warfare in stunning detail with up to 128-player battles.",
                            Genre = "PlayStation Game",
                            ImageUrl = "/images/playstation/games/battlefield-6.png",
                            Platform = "PS5/PS4",
                            Price = 50m,
                            ReleaseDate = "October 2025",
                            Slug = "battlefield-6",
                            Title = "Battlefield 6"
                        },
                        new
                        {
                            Id = 72,
                            Category = "PlayStation Games",
                            Description = "Rip and tear through the medieval hellscapes of this intense Doom prequel.",
                            Genre = "PlayStation Game",
                            ImageUrl = "/images/playstation/games/doom-dark-ages.png",
                            Platform = "PS5/PS4",
                            Price = 55m,
                            ReleaseDate = "May 2025",
                            Slug = "doom-dark-ages",
                            Title = "Doom: The Dark Ages"
                        },
                        new
                        {
                            Id = 73,
                            Category = "PlayStation Games",
                            Description = "Step into the world of professional hockey with enhanced physics and new career modes.",
                            Genre = "PlayStation Game",
                            ImageUrl = "/images/playstation/games/nhl25.png",
                            Platform = "PS5/PS4",
                            Price = 10m,
                            ReleaseDate = "October 2024",
                            Slug = "nhl-25",
                            Title = "NHL 25"
                        },
                        new
                        {
                            Id = 74,
                            Category = "PlayStation Games",
                            Description = "Venture into dark, twisted worlds in this chilling and emotional horror platformer.",
                            Genre = "PlayStation Game",
                            ImageUrl = "/images/playstation/games/little-nightmares-3.png",
                            Platform = "PS5/PS4",
                            Price = 35m,
                            ReleaseDate = "October 2025",
                            Slug = "little-nightmares-3",
                            Title = "Little Nightmares III"
                        },
                        new
                        {
                            Id = 75,
                            Category = "PlayStation Games",
                            Description = "Explore vast landscapes and hunt incredible beasts in this next-gen Monster Hunter adventure.",
                            Genre = "PlayStation Game",
                            ImageUrl = "/images/playstation/games/monster-hunter-wilds.png",
                            Platform = "PS5/PS4",
                            Price = 25m,
                            ReleaseDate = "February 2025",
                            Slug = "monster-hunter-wilds",
                            Title = "Monster Hunter Wilds"
                        },
                        new
                        {
                            Id = 76,
                            Category = "PlayStation New In",
                            Description = "Uncover the mysteries of the snowy island in this action-adventure game.",
                            Genre = "PlayStation New In",
                            ImageUrl = "/images/playstation/newin/ghost-of-yotei.png",
                            Platform = "PS5/PS4",
                            Price = 69.99m,
                            ReleaseDate = "October 2025",
                            Slug = "ghost-of-yotei",
                            Title = "Ghost of Yōtei"
                        },
                        new
                        {
                            Id = 77,
                            Category = "PlayStation New In",
                            Description = "Join elite raiders in tactical cooperative missions.",
                            Genre = "PlayStation New In",
                            ImageUrl = "/images/playstation/newin/arc-raiders.png",
                            Platform = "PS5/PS4",
                            Price = 49.99m,
                            ReleaseDate = "October 2025",
                            Slug = "arc-raiders",
                            Title = "ARC Raiders"
                        },
                        new
                        {
                            Id = 78,
                            Category = "PlayStation New In",
                            Description = "Manage your park and dinosaurs in stunning detail.",
                            Genre = "PlayStation New In",
                            ImageUrl = "/images/playstation/newin/jurassic-world-evolution-3.png",
                            Platform = "PS5/PS4",
                            Price = 49.99m,
                            ReleaseDate = "October 2025",
                            Slug = "jurassic-world-evolution-3",
                            Title = "Jurassic World Evolution 3"
                        },
                        new
                        {
                            Id = 79,
                            Category = "PlayStation New In",
                            Description = "Continue the epic journey in Hideo Kojima's sequel.",
                            Genre = "PlayStation New In",
                            ImageUrl = "/images/playstation/newin/death-stranding-2.png",
                            Platform = "PS5/PS4",
                            Price = 54.99m,
                            ReleaseDate = "June 2025",
                            Slug = "death-stranding-2",
                            Title = "Death Stranding 2: On the Beach"
                        },
                        new
                        {
                            Id = 80,
                            Category = "PlayStation New In",
                            Description = "Return to iconic Black Ops multiplayer battles.",
                            Genre = "PlayStation New In",
                            ImageUrl = "/images/playstation/newin/cod-black-ops-7.png",
                            Platform = "PS5/PS4",
                            Price = 59.99m,
                            ReleaseDate = "November 2025",
                            Slug = "cod-black-ops-7",
                            Title = "Call of Duty: Black Ops 7"
                        },
                        new
                        {
                            Id = 81,
                            Category = "PlayStation New In",
                            Description = "Dive into the dark vampire underworld of Seattle.",
                            Genre = "PlayStation New In",
                            ImageUrl = "/images/playstation/newin/vampire-bloodlines-2.png",
                            Platform = "PS5/PS4",
                            Price = 49.99m,
                            ReleaseDate = "October 2025",
                            Slug = "vampire-bloodlines-2",
                            Title = "Vampire: The Masquerade – Bloodlines 2"
                        },
                        new
                        {
                            Id = 82,
                            Category = "PlayStation New In",
                            Description = "Classic beat ‘em up action remastered.",
                            Genre = "PlayStation New In",
                            ImageUrl = "/images/playstation/newin/double-dragon-revive.png",
                            Platform = "PS5/PS4",
                            Price = 35.95m,
                            ReleaseDate = "October 2025",
                            Slug = "double-dragon-revive",
                            Title = "Double Dragon Revive Limited Edition"
                        },
                        new
                        {
                            Id = 83,
                            Category = "PlayStation New In",
                            Description = "Time-traveling Digimon adventure.",
                            Genre = "PlayStation New In",
                            ImageUrl = "/images/playstation/newin/digimon-time-stranger.png",
                            Platform = "PS5/PS4",
                            Price = 54.99m,
                            ReleaseDate = "October 2025",
                            Slug = "digimon-time-stranger",
                            Title = "Digimon Story: Time Stranger"
                        },
                        new
                        {
                            Id = 84,
                            Category = "PlayStation New In",
                            Description = "Chilling platformer adventure.",
                            Genre = "PlayStation New In",
                            ImageUrl = "/images/playstation/newin/little-nightmares-3.png",
                            Platform = "PS5/PS4",
                            Price = 32.99m,
                            ReleaseDate = "October 2025",
                            Slug = "little-nightmares-3-newin",
                            Title = "Little Nightmares III"
                        },
                        new
                        {
                            Id = 85,
                            Category = "PlayStation New In",
                            Description = "Next-gen massive warfare action.",
                            Genre = "PlayStation New In",
                            ImageUrl = "/images/playstation/newin/battlefield-6.png",
                            Platform = "PS5/PS4",
                            Price = 69.99m,
                            ReleaseDate = "October 2025",
                            Slug = "battlefield-6-newin",
                            Title = "Battlefield 6"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Computer Accessories",
                            Description = "Lightweight gaming mouse with precision tracking and ergonomic comfort.",
                            Genre = "Computer Accessory",
                            ImageUrl = "/images/computer/accessories/hyperx-pulsefire-haste2.png",
                            Platform = "PC",
                            Price = 22.99m,
                            ReleaseDate = "April 2023",
                            Slug = "hyperx-pulsefire-haste2",
                            Title = "HyperX Pulsefire Haste 2 Gaming Mouse"
                        },
                        new
                        {
                            Id = 87,
                            Category = "Computer Accessories",
                            Description = "Connect USB-C laptops or tablets to HDMI displays in crisp 4K quality.",
                            Genre = "Computer Accessory",
                            ImageUrl = "/images/computer/accessories/usb-c-hdmi-adapter.png",
                            Platform = "PC",
                            Price = 6.13m,
                            ReleaseDate = "August 2014",
                            Slug = "usb-c-hdmi-adapter",
                            Title = "USB-C to HDMI Adapter, Type-C to HDMI 4K Adapter"
                        },
                        new
                        {
                            Id = 88,
                            Category = "Computer Accessories",
                            Description = "Premium sound and comfort for immersive PC gaming.",
                            Genre = "Computer Accessory",
                            ImageUrl = "/images/computer/accessories/hyperx-cloud-alpha.png",
                            Platform = "PC",
                            Price = 59.99m,
                            ReleaseDate = "August 2017",
                            Slug = "hyperx-cloud-alpha",
                            Title = "HyperX Cloud Alpha – Gaming Headset"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Computer Accessories",
                            Description = "Professional-grade USB microphone for streaming and podcasting.",
                            Genre = "Computer Accessory",
                            ImageUrl = "/images/computer/accessories/yeti-usb-microphone.png",
                            Platform = "PC",
                            Price = 119.00m,
                            ReleaseDate = "August 2020",
                            Slug = "yeti-usb-microphone",
                            Title = "YETI USB Streaming Microphone - Blackout"
                        },
                        new
                        {
                            Id = 90,
                            Category = "Computer Accessories",
                            Description = "Reliable HD webcam ideal for streaming or video calls.",
                            Genre = "Computer Accessory",
                            ImageUrl = "/images/computer/accessories/logitech-c310.png",
                            Platform = "PC",
                            Price = 22.50m,
                            ReleaseDate = "July 2010",
                            Slug = "logitech-c310",
                            Title = "Logitech C310 HD Webcam, 720p/30fps"
                        },
                        new
                        {
                            Id = 91,
                            Category = "Computer Console",
                            Description = "Portable PC gaming device with full Steam library support.",
                            Genre = "Computer Console",
                            ImageUrl = "/images/computer/consoles/steam-deck-256gb.png",
                            Platform = "PC",
                            Price = 354.00m,
                            ReleaseDate = "February 2022",
                            Slug = "steam-deck-256gb",
                            Title = "Steam Deck 256GB"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Computer Console",
                            Description = "High-performance handheld gaming PC powered by Windows 11.",
                            Genre = "Computer Console",
                            ImageUrl = "/images/computer/consoles/asus-rog-ally-512gb.png",
                            Platform = "PC",
                            Price = 499.00m,
                            ReleaseDate = "October 2025",
                            Slug = "asus-rog-ally-512gb",
                            Title = "ASUS ROG Ally 512GB"
                        },
                        new
                        {
                            Id = 93,
                            Category = "Computer Console",
                            Description = "Powerful portable console with detachable controllers and 8.8” QHD display.",
                            Genre = "Computer Console",
                            ImageUrl = "/images/computer/consoles/lenovo-legion-go-512gb.png",
                            Platform = "PC",
                            Price = 675.00m,
                            ReleaseDate = "October 2025",
                            Slug = "lenovo-legion-go-512gb",
                            Title = "Lenovo Legion Go 512GB"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Computer Console",
                            Description = "Intel-powered gaming handheld built for performance and portability.",
                            Genre = "Computer Console",
                            ImageUrl = "/images/computer/consoles/msi-claw-a1m-512gb.png",
                            Platform = "PC",
                            Price = 549.99m,
                            ReleaseDate = "March 2024",
                            Slug = "msi-claw-a1m-512gb",
                            Title = "MSI Claw A1M 512GB"
                        },
                        new
                        {
                            Id = 95,
                            Category = "Computer Console",
                            Description = "Compact yet powerful mini-PC ideal for gaming and creative work.",
                            Genre = "Computer Console",
                            ImageUrl = "/images/computer/consoles/zotac-zbox-magnus-er51060.png",
                            Platform = "PC",
                            Price = 785.57m,
                            ReleaseDate = "February 2018",
                            Slug = "zotac-zbox-magnus-er51060",
                            Title = "Zotac Zbox Magnus ER51060"
                        },
                        new
                        {
                            Id = 96,
                            Category = "Computer Game",
                            Description = "Sail through mysterious waters and uncover ancient secrets.",
                            Genre = "Computer Game",
                            ImageUrl = "/images/computer/games/sea-fantasy-2.png",
                            Platform = "PC",
                            Price = 15m,
                            ReleaseDate = "January 2025",
                            Slug = "sea-fantasy",
                            Title = "Sea Fantasy"
                        },
                        new
                        {
                            Id = 97,
                            Category = "Computer Game",
                            Description = "Classic RPG adventure remastered for modern systems.",
                            Genre = "Computer Game",
                            ImageUrl = "/images/computer/games/ys-memoire-2.png",
                            Platform = "PC",
                            Price = 25m,
                            ReleaseDate = "January 2025",
                            Slug = "ys-memoire",
                            Title = "Ys Memoire: The Oath in Felghana"
                        },
                        new
                        {
                            Id = 98,
                            Category = "Computer Game",
                            Description = "Battle for freedom in this post-apocalyptic action RPG.",
                            Genre = "Computer Game",
                            ImageUrl = "/images/computer/games/freedom-wars-remastered-2.png",
                            Platform = "PC",
                            Price = 16m,
                            ReleaseDate = "January 2025",
                            Slug = "freedom-wars-remastered",
                            Title = "Freedom Wars Remastered"
                        },
                        new
                        {
                            Id = 99,
                            Category = "Computer Game",
                            Description = "Run a magical tavern in a world full of potions, spells, and adventure.",
                            Genre = "Computer Game",
                            ImageUrl = "/images/computer/games/magic-inn-2.png",
                            Platform = "PC",
                            Price = 15m,
                            ReleaseDate = "August 2025",
                            Slug = "magic-inn",
                            Title = "Magic INN"
                        },
                        new
                        {
                            Id = 100,
                            Category = "Computer Game",
                            Description = "Explore the Overgrowth in this open-world roguelike action game.",
                            Genre = "Computer Game",
                            ImageUrl = "/images/computer/games/hyper-light-breaker-2.png",
                            Platform = "PC",
                            Price = 30m,
                            ReleaseDate = "January 2025",
                            Slug = "hyper-light-breaker",
                            Title = "Hyper Light Breaker"
                        },
                        new
                        {
                            Id = 101,
                            Category = "Computer New In",
                            Description = "Return to Pandora for an explosive new looter-shooter experience.",
                            Genre = "Computer New In",
                            ImageUrl = "/images/computer/newin/borderlands-4.png",
                            Platform = "PC",
                            Price = 58m,
                            ReleaseDate = "September 2025",
                            Slug = "borderlands-4",
                            Title = "Borderlands 4"
                        },
                        new
                        {
                            Id = 102,
                            Category = "Computer New In",
                            Description = "Build, defend, and manage your dungeons in this dark fantasy adventure.",
                            Genre = "Computer New In",
                            ImageUrl = "/images/computer/newin/keeper.png",
                            Platform = "PC",
                            Price = 49.99m,
                            ReleaseDate = "November 2025",
                            Slug = "keeper",
                            Title = "Keeper"
                        },
                        new
                        {
                            Id = 103,
                            Category = "Computer New In",
                            Description = "Fast-paced hack-and-slash action returns with new mechanics.",
                            Genre = "Computer New In",
                            ImageUrl = "/images/computer/newin/ninja-gaiden-4.png",
                            Platform = "PC",
                            Price = 59.99m,
                            ReleaseDate = "October 2025",
                            Slug = "ninja-gaiden-4",
                            Title = "Ninja Gaiden 4"
                        },
                        new
                        {
                            Id = 104,
                            Category = "Computer New In",
                            Description = "Immerse yourself in the dark vampire world of Seattle.",
                            Genre = "Computer New In",
                            ImageUrl = "/images/computer/newin/vampire-the-masquerade-bloodlines-2.png",
                            Platform = "PC",
                            Price = 54.99m,
                            ReleaseDate = "October 2025",
                            Slug = "vampire-the-masquerade-bloodlines-2",
                            Title = "Vampire: The Masquerade - Bloodlines 2"
                        },
                        new
                        {
                            Id = 105,
                            Category = "Computer New In",
                            Description = "Team up and fight back against robotic threats in this co-op shooter.",
                            Genre = "Computer New In",
                            ImageUrl = "/images/computer/newin/arc-raiders.png",
                            Platform = "PC",
                            Price = 49.99m,
                            ReleaseDate = "October 2025",
                            Slug = "arc-raiders",
                            Title = "ARC Raiders"
                        },
                        new
                        {
                            Id = 106,
                            Category = "Computer New In",
                            Description = "A new chapter in the Digimon Story RPG series.",
                            Genre = "Computer New In",
                            ImageUrl = "/images/computer/newin/digimon-time-stranger.png",
                            Platform = "PC",
                            Price = 54.99m,
                            ReleaseDate = "October 2025",
                            Slug = "digimon-time-stranger",
                            Title = "Digimon Story: Time Stranger"
                        },
                        new
                        {
                            Id = 107,
                            Category = "Computer New In",
                            Description = "Embark on a satirical sci-fi adventure across the stars.",
                            Genre = "Computer New In",
                            ImageUrl = "/images/computer/newin/outer-worlds-2.png",
                            Platform = "PC",
                            Price = 59.99m,
                            ReleaseDate = "October 2025",
                            Slug = "outer-worlds-2",
                            Title = "The Outer Worlds 2"
                        },
                        new
                        {
                            Id = 108,
                            Category = "Computer New In",
                            Description = "Defend your butcher empire in this over-the-top combat game.",
                            Genre = "Computer New In",
                            ImageUrl = "/images/computer/newin/king-of-meat.png",
                            Platform = "PC",
                            Price = 38.99m,
                            ReleaseDate = "October 2025",
                            Slug = "king-of-meat",
                            Title = "King of Meat"
                        },
                        new
                        {
                            Id = 109,
                            Category = "Computer New In",
                            Description = "The ultimate baseball simulation for fans of the sport.",
                            Genre = "Computer New In",
                            ImageUrl = "/images/computer/newin/professional-baseball-spirits.png",
                            Platform = "PC",
                            Price = 90m,
                            ReleaseDate = "October 2024",
                            Slug = "professional-baseball-spirits",
                            Title = "Professional Baseball Spirits (Korean Version)"
                        },
                        new
                        {
                            Id = 110,
                            Category = "Computer New In",
                            Description = "Race to victory in the newest installment of the NASCAR series.",
                            Genre = "Computer New In",
                            ImageUrl = "/images/computer/newin/nascar-25-pc.png",
                            Platform = "PC",
                            Price = 40m,
                            ReleaseDate = "October 2025",
                            Slug = "nascar-25",
                            Title = "NASCAR 25 (PC)"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
